# Generated by Django 3.0.7 on 2020-07-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20200712_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='url_name',
            field=models.SlugField(unique=True),
        ),
    ]
